#!/bin/bash
#SBATCH --time=15:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --account=PAS1730

#module load intel-oneapi-mpi/2021.10.0
module load python/3.12
#module load matlab/r2024a

#export I_MPI_SPAWN=on
set -x

PROJECT_ROOT="/users/PAS1730/ziyaosu816/Desktop/ProjectSpace/GratingOptimization/GratingOpt"

cd "$PROJECT_ROOT"

export PYTHONPATH="$PROJECT_ROOT/src:$PYTHONPATH"

python -u -m grating_opt.main
# srun python -u -m grating_opt.main