duty_cycle:
  lb: 0.4
  ub: 0.6
  parameter_type: float

pillar_thickness:
  lb: 1200
  ub: 1475
  parameter_type: float

residual_thickness:
 lb: 90
 ub: 110
 parameter_type: float

lines_per_mm:
 lb: 550
 ub: 650
 parameter_type: float

aoi:
  lb: 34.36623   # [degrees]
  ub: 40.5    # [degrees]
  parameter_type: float

slope_angle:
  lb: 0.0   # [degrees]
  ub: 5.0   # [degrees]
  parameter_type: float