dc:
  lb: 0.4
  ub: 0.6
  parameter_type: float

tp:
  lb: 1200
  ub: 1475
  parameter_type: float

tr:
 lb: 0
 ub: 200
 parameter_type: float

lmm:
 lb: 550
 ub: 650
 parameter_type: float

aoi:
  lb: 34.36623   # [degrees]
  ub: 40.5    # [degrees]
  parameter_type: float

sa:
  lb: 75.0   # [degrees]
  ub: 90.0   # [degrees]
  parameter_type: float